version: "3.7"

services:
  app:
    image: paulomarcio/php-fpm-7.3
    container_name: tdd-leilao
    working_dir: /var/www/
    volumes:
      - /home/lu/estudos/tdd-leilao:/var/www
    networks:
      - tdd

  nginx:
    image: nginx:1.17-alpine
    container_name: tdd-leilao-nginx
    ports:
      - "${PORT}:80"
    volumes:
      - /home/lu/estudos/tdd-leilao:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - tdd

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - tdd

networks:
  tdd:
    name: tdd
    driver: bridge
    external: true
